swagger: '2.0'
info:
  description: ''
  version: 1.0.0
  title: HBCC Time Table
host: localhost
basePath: /api
tags:
  - name: access_tokens
    description: ''
  - name: users
    description: ''
  - name: events
    description: ''
paths:
  /users:
    post:
      tags:
        - users
      summary: Add a new user
      description: ''
      operationId: addUser
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: Information about new user
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: 'Success: user added'
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Bad request
          schema:
            $ref: '#/definitions/ApiResponse'
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
    flow: implicit
    scopes:
      'write:pets': modify pets in your account
      'read:pets': read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  User:
    type: object
    properties:
      id:
        type: string
        required: false
      email:
        type: string
        pattern: '^[_a-z0-9-]+(\\.[_a-z0-9-]+)*@[a-z0-9-]+(\\.[a-z0-9-]+)+$'
        description: 'The email of the user. Shoul be format as an email.'
      firstName:
        type: string
        description: The first name of the user.
      lastName:
        type: string
        description: The last name of the user.
      plainPassword:
        type: string
        description: The plain password of the user.
      speciality:
        type: string
        description: Id of the user speciality.
  Speciality:
    type: object
    properties:
      name:
        type: string
      url:
        type: string
  Event:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      location:
        type: string
      beginDate:
        type: string
      endDate:
        type: string
  Access_token:
    type: object
    properties:
      token:
        type: string
      expires_at:
        type: string
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
